import React, { useState, useEffect } from 'react';
import client from '../api/client';
import ReactMarkdown from 'react-markdown';
import { Sparkles, Send, LayoutDashboard, Brain, AlertTriangle, Lightbulb, TrendingUp } from 'lucide-react';
import clsx from 'clsx';
import toast from 'react-hot-toast';

const AIAdvisor = () => {
  const [projects, setProjects] = useState([]);
  const [selectedProjectId, setSelectedProjectId] = useState('all');
  const [advice, setAdvice] = useState('');
  const [isLoading, setIsLoading] = useState(false);

  useEffect(() => {
    const fetchProjects = async () => {
      try {
        const res = await client.get('/dashboard/projects');
        if (res.data.success) {
          setProjects(res.data.projects);
        }
      } catch (err) {
        console.error('Failed to fetch projects', err);
      }
    };
    fetchProjects();
  }, []);

  const handleGetAdvice = async () => {
    setIsLoading(true);
    setAdvice('');
    try {
      const res = await client.get(`/ai/advisor?projectId=${selectedProjectId}`);
      if (res.data.success) {
        setAdvice(res.data.advice);
      }
    } catch (err) {
      toast.error('Failed to generate AI advice');
      console.error(err);
    } finally {
      setIsLoading(false);
    }
  };

  return (
    <div className="space-y-6 max-w-5xl mx-auto">
      <div className="flex flex-col md:flex-row md:items-center justify-between gap-4">
        <div>
          <h1 className="text-2xl font-bold text-white flex items-center gap-2">
            <Sparkles className="w-7 h-7 text-brand-400" />
            AI Advisor
          </h1>
          <p className="text-slate-400 mt-1">
            Analyzing your error trends to provide architectural insights and reliability recommendations.
          </p>
        </div>

        <div className="flex gap-3">
          <select
            value={selectedProjectId}
            onChange={(e) => setSelectedProjectId(e.target.value)}
            className="bg-dark-800 border border-slate-700 text-slate-200 text-sm rounded-xl px-4 py-2 outline-none focus:border-brand-500 transition-all cursor-pointer"
          >
            <option value="all">All Projects</option>
            {projects.map(p => (
              <option key={p.id} value={p.id}>{p.name}</option>
            ))}
          </select>
          <button
            onClick={handleGetAdvice}
            disabled={isLoading}
            className="btn-primary flex items-center gap-2 px-6 shadow-lg shadow-brand-500/20 disabled:opacity-50"
          >
            {isLoading ? (
              <div className="w-4 h-4 border-2 border-white/30 border-t-white rounded-full animate-spin" />
            ) : (
              <Brain className="w-4 h-4" />
            )}
            {isLoading ? 'Thinking...' : 'Get Advice'}
          </button>
        </div>
      </div>

      {!advice && !isLoading ? (
        <div className="glass-panel p-16 text-center space-y-4">
          <div className="w-20 h-20 bg-brand-500/10 rounded-full flex items-center justify-center mx-auto mb-6">
            <Lightbulb className="w-10 h-10 text-brand-400" />
          </div>
          <h3 className="text-xl font-bold text-white">Ready to optimize your architecture?</h3>
          <p className="text-slate-500 max-w-lg mx-auto">
            Our AI Advisor will scan the last 48 hours of error logs to identify patterns, 
            root causes, and provide you with a prioritized action plan.
          </p>
          <button
            onClick={handleGetAdvice}
            className="text-brand-400 hover:text-brand-300 font-medium text-sm transition-colors"
          >
            Click here to start analysis
          </button>
        </div>
      ) : (
        <div className={clsx(
          "glass-panel overflow-hidden transition-all duration-500",
          isLoading ? "opacity-50 scale-[0.98] blur-[2px]" : "opacity-100 scale-100 blur-0"
        )}>
          <div className="bg-brand-500/5 px-6 py-4 border-b border-white/5 flex items-center justify-between">
            <div className="flex items-center gap-2 text-brand-400 text-sm font-bold uppercase tracking-wider">
              <TrendingUp className="w-4 h-4" />
              Strategic Report
            </div>
            <div className="text-[10px] text-slate-500">
              Generated by NodeWatch AI • {new Date().toLocaleDateString()}
            </div>
          </div>
          
          <div className="p-8 prose prose-invert max-w-none prose-headings:text-white prose-p:text-slate-300 prose-strong:text-brand-300 prose-code:text-emerald-400">
            <style dangerouslySetInnerHTML={{ __html: `
              .markdown-content h1 { font-size: 1.5rem; font-weight: 700; margin-bottom: 1.5rem; color: white; }
              .markdown-content h2 { font-size: 1.25rem; font-weight: 600; margin-top: 2rem; margin-bottom: 1rem; color: #f8fafc; border-bottom: 1px solid rgba(255,255,255,0.05); padding-bottom: 0.5rem; }
              .markdown-content h3 { font-size: 1.1rem; font-weight: 600; margin-top: 1.5rem; margin-bottom: 0.75rem; color: #e2e8f0; }
              .markdown-content p { margin-bottom: 1rem; line-height: 1.6; color: #94a3b8; }
              .markdown-content ul { list-style-type: disc; margin-left: 1.5rem; margin-bottom: 1.5rem; }
              .markdown-content li { margin-bottom: 0.5rem; color: #94a3b8; }
              .markdown-content strong { color: #818cf8; font-weight: 600; }
              .markdown-content code { background: rgba(0,0,0,0.3); padding: 0.2rem 0.4rem; rounded: 4px; font-family: monospace; color: #34d399; font-size: 0.9em; }
            `}} />
            <div className="markdown-content">
              <ReactMarkdown>{advice}</ReactMarkdown>
            </div>
          </div>
        </div>
      )}

      {/* Info Cards */}
      <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
        <div className="glass-panel p-5 space-y-2">
          <div className="p-2 w-fit rounded-lg bg-emerald-500/10 text-emerald-400">
            <TrendingUp className="w-5 h-5" />
          </div>
          <h4 className="text-sm font-bold text-white">Trend Analysis</h4>
          <p className="text-xs text-slate-500">Detects spike patterns and identifies if issues are increasing or stabilizing.</p>
        </div>
        <div className="glass-panel p-5 space-y-2">
          <div className="p-2 w-fit rounded-lg bg-blue-500/10 text-blue-400">
            <Brain className="w-5 h-5" />
          </div>
          <h4 className="text-sm font-bold text-white">Root Cause Correlation</h4>
          <p className="text-xs text-slate-500">Links disparate error logs to find common underlying infrastructure failures.</p>
        </div>
        <div className="glass-panel p-5 space-y-2">
          <div className="p-2 w-fit rounded-lg bg-purple-500/10 text-purple-400">
            <Lightbulb className="w-5 h-5" />
          </div>
          <h4 className="text-sm font-bold text-white">Actionable ROI</h4>
          <p className="text-xs text-slate-500">Focuses your engineering effort on the issues with the highest impact on users.</p>
        </div>
      </div>
    </div>
  );
};

export default AIAdvisor;
